version: "3.7"
services:
  nginx_server:
    image: custom-nginx
    ports:
      - "80:80"
    networks:
      - demo-network
    depends_on:
      - "teams-backend"
  teams-backend:
    image: teams-backend:latest
    ports:
      - "8080:8080"
    networks:
      - demo-network

networks:
  demo-network:
    name: demo-network
